# Generated by Django 4.0.5 on 2022-06-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='course',
            new_name='Item',
        ),
    ]
