# Generated by Django 4.0.5 on 2022-06-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerapi', '0004_remove_item_discount_offer_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Item',
            new_name='product',
        ),
    ]
