# Generated by Django 4.0.5 on 2022-06-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerapi', '0005_rename_item_offer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='product',
            new_name='ItemSerializer',
        ),
    ]
