# Generated by Django 4.0.5 on 2022-06-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerapi', '0006_rename_product_offer_itemserializer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='ItemSerializer',
            new_name='Item',
        ),
    ]
